package bit2shift.autoauth.loader;

import java.util.Arrays;

import com.google.common.eventbus.EventBus;
import com.google.common.eventbus.Subscribe;

import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;
import cpw.mods.fml.common.event.FMLInitializationEvent;
import cpw.mods.fml.common.event.FMLPostInitializationEvent;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;

public class SpicyContainer extends DummyModContainer
{
	private String getVersion(boolean full)
	{
		return String.format("#${project.version}-%s", "N/A");
	}

	public SpicyContainer()
	{
		super(new ModMetadata());
		ModMetadata meta = this.getMetadata();
		meta.modId = "AutoAuth";
		meta.name = "AutoAuth (Loader, Core)";
		meta.version = this.getVersion(true);
		meta.authorList = Arrays.asList("bit2shift");
		meta.description = "Community bridge, noob filter, server-side skins/capes and spambot firewall (future feature)";
		meta.credits = "LargePrime, Payner94 and all @ #minecraftforge";
		meta.url = "https://github.com/bit2shift/AutoAuth";
		meta.logoFile = "/logo.png";
		meta.autogenerated = false;
	}

	@Override
	public String getDisplayVersion()
	{
		return this.getVersion(false);
	}

	@Override
	public boolean registerBus(EventBus bus, LoadController controller)
	{
		bus.register(this);
		return true;
	}

	@Subscribe
	public void preInit(FMLPreInitializationEvent event)
	{
	}

	@Subscribe
	public void init(FMLInitializationEvent event)
	{
	}

	@Subscribe
	public void postInit(FMLPostInitializationEvent event)
	{
	}
}
